baseurl: ""
url: nicholasrhodes.co.uk
harmony:
  name: Nicholas Rhodes
  description: ''
  meta_description: >
    Random posts on Linux
  social:
    github: https://github.com/nrhodes91
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude:
  - .gitignore
  - .sass-cache
sass:
    sass_dir: assets/css/_sass
    style: :compressed
