version: 0.2
env:
  variables:
     JEKYLL_VERSION: 3.8
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - docker --version
      - docker pull jekyll/builder:$JEKYLL_VERSION
  pre_build:
    commands:
      - chown -R 1000:1000 $CODEBUILD_SRC_DIR
  build:
    commands:
      - docker run --rm --volume="$CODEBUILD_SRC_DIR:/srv/jekyll" jekyll/builder:$JEKYLL_VERSION jekyll build
  post_build:
    commands:
      - ls -la
      - cp -a .ebextensions _site/
artifacts:
  files:
    - '**/*'
  base-directory: _site/
